[package]
name = "cubetonic"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.1", features = ["derive"] }
env_logger = "0.11.8"
pollster = "0.4.0"
rand = "0.9.2"
wgpu = "26.0.1"
winit = "0.30.11"
